// models/Captain.js
const mongoose = require('mongoose');

const CaptainSchema = new mongoose.Schema({
    captainId: { type: String, required: true, unique: true }, // auto-generated by backend
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false }, // ✅ link to User
    name: { type: String, required: true }, 
    branch: { type: String, required: true }, 
    urn: { type: String, required: true, unique: true }, 
    year: { type: Number, required: true }, 
    sport: { type: String, required: true }, 
    teamMemberCount: { type: Number, required: true },

    // Filled by captain on first login
    email: { type: String },
    phone: { type: String },
    position: { type: String, default:"pending" }, // ✅ captain's position
     certificateAvailable: { type: Boolean, default: false },
    // After first form submission → team member info
    teamMembers: [
        {
            name: { type: String, required: true },
            branch: { type: String, required: true },
            urn: { type: String, required: true },
            year: { type: Number, required: true },
            email: { type: String, required: true },
            phone: { type: String, required: true }
        }
    ],

    session: { type: mongoose.Schema.Types.ObjectId, ref: "Session", required: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model("Captain", CaptainSchema);
