const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  name: String,
  email: { type: String, unique: true },
  password: String,
  roles: { 
    type: [String], 
    enum: ['admin', 'teacher', 'student', 'captain'], 
    required: true 
  },
  studentProfile: { type: mongoose.Schema.Types.ObjectId, ref: 'StudentProfile' },

  // Captain-specific (assigned by admin)
  captainId: { type: String, unique: true, sparse: true }, // auto-generated by admin
  branch: { type: String },
  urn: { type: String },
  year: { type: String },
  sport: { type: String },
  teamMemberCount: { type: Number },
  
  // Filled later by captain
  captainProfile: { type: mongoose.Schema.Types.ObjectId, ref: 'CaptainProfile' }
}, 
{ timestamps: true });

module.exports = mongoose.model('User', UserSchema);
